spring:
  profiles:
    group:
      local: "h2"
      mysql: "mysql"
  batch:
    job:
      name: ${job.name:NONE}

---

spring:
  config:
    activate:
      on-profile: "h2"

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:


---

spring:
  config:
    activate:
      on-profile: "mysql"

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:13306/batch
    username: test
    password: test1234